export {
  ProductClient,
  type ClientOptions,
  type ConnectOptions,
  RealtimeURLMismatchError,
  fetchAppConfig,
  AuthPersistenceError,
  createAuthStore,
  type PersistentAuthStore,
  ClientTooOldError,
  ConfigFetchError,
  createMemoryStorage,
  type HostStorageApi,
  type PlatformAdapters,
  type StorageAdapter,
  createWebStorage,
  createDesktopStorage,
  type DesktopStorageApi,
  createMobileStorage,
  type MobileStorageApi,
  compareVersions,
  isClientCompatible,
} from "@lattice/sdk";
