import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv from "ajv";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile } from "json-schema-to-typescript";
import { build } from "esbuild";

const root = resolve(fileURLToPath(new URL("../..", import.meta.url)));
const check = process.argv.includes("--check");
const schemasDir = resolve(root, "contracts/schemas");
const outDir = resolve(root, "packages/types/src/generated");
const schemaSpecs = [
  ["AppConfig", "contracts/schemas/app-config.json", "app-config.json"],
  ["Features", "contracts/schemas/features.json", "features.json"],
  ["DashboardLayout", "contracts/schemas/dashboard-layout.json", "dashboard-layout.json"],
  ["PluginManifest", "contracts/schemas/plugin-manifest.json", "plugin-manifest.json"],
  ["EventEnvelope", "contracts/schemas/events/envelope.json", "events/envelope.json"],
];

async function output(path, content) {
  if (check) {
    let current;
    try { current = await readFile(path, "utf8"); } catch { current = undefined; }
    if (current !== content) throw new Error(`Generated file is stale: ${relative(root, path)}`);
    return;
  }
  await mkdir(resolve(path, ".."), { recursive: true });
  await writeFile(path, content, "utf8");
}

const schemas = [];
for (const [name, source, outputName] of schemaSpecs) {
  const schema = JSON.parse(await readFile(resolve(root, source), "utf8"));
  schemas.push({ name, schema, outputName });
}

let typeText = "// Generated by tools/codegen/gen.mjs. Do not edit.\n";
for (const { name, schema } of schemas) {
  typeText += `\n${await compile(schema, name, { bannerComment: "", style: { singleQuote: true } })}`;
}
await output(resolve(outDir, "types.ts"), typeText);

const schemaText = `// Generated by tools/codegen/gen.mjs. Do not edit.\n${schemas
  .map(({ name, schema }) => `export const ${name[0].toLowerCase()}${name.slice(1)}Schema = ${JSON.stringify(schema, null, 2)} as const;`)
  .join("\n\n")}\n`;
await output(resolve(outDir, "schemas.ts"), schemaText);

const ajv = new Ajv({ allErrors: true, strict: true, allowUnionTypes: true, code: { source: true, esm: true } });
addFormats(ajv);
for (const { schema } of schemas) ajv.addSchema(schema);
const validatorMap = Object.fromEntries(schemas.map(({ name, schema }) => [`validate${name}`, schema.$id]));
let validatorCode = standaloneCode(ajv, validatorMap);
const bundled = await build({
  absWorkingDir: root,
  stdin: { contents: validatorCode, resolveDir: root, sourcefile: "standalone.js", loader: "js" },
  bundle: true,
  platform: "browser",
  format: "esm",
  target: ["es2022"],
  write: false,
});
validatorCode = bundled.outputFiles[0].text;
if (/^import .* from ["'](?:node:|fs|path)/m.test(validatorCode)) {
  throw new Error("Bundled standalone validators contain a Node-only import");
}
await output(resolve(outDir, "standalone.mjs"), validatorCode);
await output(resolve(outDir, "standalone.d.mts"), `// Generated by tools/codegen/gen.mjs. Do not edit.\n${schemas.map(({ name }) => `export declare const validate${name}: { (data: unknown): boolean; errors?: Array<{ instancePath?: string; message?: string }> | null };`).join("\n")}\n`);

const goDir = resolve(root, "backend/internal/platform/tenant");
const goBundle = `// Code generated by tools/codegen/gen.mjs; DO NOT EDIT.\npackage tenant\n\nvar schemaDocuments = map[string]string{\n${schemas
  .map(({ name, schema }) => `\t${JSON.stringify(name)}: ${JSON.stringify(JSON.stringify(schema))},`)
  .join("\n")}\n}\n`;
await output(resolve(goDir, "schema_bundle.go"), goBundle);

if (!check) console.log(`Generated ${schemas.length} TypeScript contracts, standalone validators, and Go schemas.`);
else console.log("Generated TypeScript and Go contract artifacts are current.");
